@startuml casosDeUso
left to right direction

' Definición de actores
actor Usuario
actor Administrador

' Contenedor principal para los casos de uso del sistema
package "Sabor Central UCV" {
    (Iniciar sesión)
    (Consultar menú)
    (Registrar usuario)
    (Gestionar menú semanal)
    (Registrar consumo diario)
    (Generar reportes)      
}

' Relaciones entre actores y casos de uso
Usuario -- (Iniciar sesión)
Usuario -- (Consultar menú)
Usuario -- (Registrar usuario)

Administrador -- (Iniciar sesión)
Administrador -- (Gestionar menú semanal)
Administrador -- (Registrar consumo diario)
Administrador -- (Generar reportes)

' Relaciones extend/include
(Generar reportes) <.. (Registrar consumo diario) : <<extend>>
@enduml