@startuml casosDeUso
left to right direction

actor BD
actor Estudiante
actor Empleado
actor Usuario
actor AdministradorComedor

rectangle "DinnerSys" {

    usecase "Registrar Usuario" as UC1
    usecase "Consultar Menú" as UC2
    usecase "Gestionar Menús Semanales" as UC3
    usecase "Registrar Consumo Diario" as UC4
    usecase "Generar Reportes" as UC5
    usecase "Iniciar Sesión" as UC6

    Estudiante -up-|> Usuario
    Empleado -up-|> Usuario

    Usuario -right- UC1
    Usuario -right- UC2
    Usuario -up- UC6
    
    AdministradorComedor -- UC1
    AdministradorComedor -- UC3
    AdministradorComedor -- UC4
    AdministradorComedor -- UC5
    AdministradorComedor - UC6
    
    BD -- UC1

    UC3 ..> UC6 : <<extend>>

    UC4 ..> UC6 : <<extend>>
    UC4 <. UC5 : <<include>>

    UC6 .> UC1 : <<include>>
    UC6 <.. UC2 : <<extend>> 
    
}
@enduml